# THIS FILE IS FOR LOCAL DEVELOPMENT ONLY
version: '3.8'
services:
  web:
    build: ./
    ports:
      - "8080:8080"
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal