package chorestogetherapiservice.verifier;

import chorestogetherapiservice.domain.SocialIdToken;
import java.util.Optional;

/**
 * ID token verifier interface verifying the ID token generated by its social service (e.x. Google)
 * */
public interface SocialIdTokenVerifier {
  Optional<String> verify(SocialIdToken socialIdToken);
}
